### PR TITLE
dev-db/metabase-bin: Bump

### PR DESCRIPTION
**Pull request by patricklauer**
Package-Manager: Portage-2.3.84, Repoman-2.3.20

### CODE REVIEW

**Comment by lemanchester** [comment]
This PR is related to https://github.com/adjust/infrastructure/issues/7203 

Currently on metabase role we don`t specify the version:
https://github.com/adjust/infrastructure/blob/master/cmdb/roles/analytics.yml#L21-L22

Won't be a problem if this gets merged? We could accidentally upgrade the metabase version and break it? 

I'm not sure, that's why I´m asking

**Comment by maxeaubrey** [comment]
We can merge this with better keywords, this but we cannot use this until the relevant plugins are updated.

**Review by lemanchester — APPROVED** [review]

**Comment by xmhd** [comment]
wdyt @alip @monsieurp @varilci ? as per Maxine's previous comments , this can't actually be used until plugins are updated. Do we need it?

cc @lemanchester

**Comment by lemanchester** [comment]
Hey @xmhd we can actually merge this, we have the following versions running already:

dev-db/metabase-bin-0.37.4
dev-db/metabase-clickhouse-driver-bin-0.7.3

I think I closed the issue and totally forgot to merge this one, sorry.

**Comment by xmhd** [comment]
> Hey @xmhd we can actually merge this, we have the following versions running already:
> 
> dev-db/metabase-bin-0.37.4
> dev-db/metabase-clickhouse-driver-bin-0.7.3
> 
> I think I closed the issue and totally forgot to merge this one, sorry.

So wrt maxine's reply (Jan 2020), we don't need to update any more plugins etc?

**Comment by lemanchester** [comment]
> > Hey @xmhd we can actually merge this, we have the following versions running already:
> > dev-db/metabase-bin-0.37.4
> > dev-db/metabase-clickhouse-driver-bin-0.7.3
> > I think I closed the issue and totally forgot to merge this one, sorry.
> 
> So wrt maxine's reply (Jan 2020), we don't need to update any more plugins etc?
> 
> edit: v0.39 is latest release from upstream - do we want to include that?

just to be clear, the plugin it is this metabase-clickhouse-driver; we had to wait the clickhouse to get compatible with metabase 0.37 for the update;

looking the metabase-clickhouse-driver repo, only the 0.38 is compatible so we don't need to include 0.39 for now.

 source: https://github.com/enqueue/metabase-clickhouse-driver

**Comment by xmhd** [comment]
> > > Hey @xmhd we can actually merge this, we have the following versions running already:
> > > dev-db/metabase-bin-0.37.4
> > > dev-db/metabase-clickhouse-driver-bin-0.7.3
> > > I think I closed the issue and totally forgot to merge this one, sorry.
> > 
> > 
> > So wrt maxine's reply (Jan 2020), we don't need to update any more plugins etc?
> > edit: v0.39 is latest release from upstream - do we want to include that?
> 
> just to be clear, the plugin it is this metabase-clickhouse-driver; we had to wait the clickhouse to get compatible with metabase 0.37 for the update;
> 
> looking the metabase-clickhouse-driver repo, only the 0.38 is compatible so we don't need to include 0.39 for now.
> 
> source: https://github.com/enqueue/metabase-clickhouse-driver

ack.

i will update this pr tomorrow, and update metabase-clickhouse-driver to latest 0.7.x release (this PR currently contains v0.7.0, upstream is v0.7.5 iirc).

**Pull request merged**
