### PR TITLE
sys-kernel: Bump to kernel 4.11

### PR DESCRIPTION
**Pull request by patricklauer**
New kernel version.
Adds bcache support once more.
Switch default IO scheduler to deadline

### CODE REVIEW

**Comment by jolenzy** [comment]
Looks good :+1: 
I'm curious to see the impact of deadline scheduler.

**Comment by patricklauer** [comment]
On the elastic indexers it gave us a noticeable boost (~20% under heavy load), I expect it to be less for other machines (and we can always manually override if required)

**Comment by jolenzy** [comment]
Okay, that sounds great :)

**Comment by patricklauer** [comment]
There's still some weirdness that I haven't had time to debug, with 4.12 on the horizon I don't think we'll fix this. Closing

**Pull request closed without merging**
