### PR TITLE
first stab at infrastructure-meta ebuild

### PR DESCRIPTION
**Pull request by xmhd**
First stab at creating a meta package for all Perl modules required to use the infrastructure repository.

There are a few TODOS in there (e.g. LICENSE and HOMEPAGE), and the category + name of the package is meh, so feel free to suggest a better alternative.

If I have missed anything, please let me know and I can update  the DEPEND list.

### CODE REVIEW

**Comment by monsieurp** [comment]
I'd actually put the package in the `virtual` category and use a more meaningful package name, something like: `virtual/adjust-infrastructure`. What do you think?

**Comment by xmhd** [comment]
> I'd actually put the package in the `virtual` category and use a more meaningful package name, something like: `virtual/adjust-infrastructure`. What do you think?

I never put it in the virtual category because afaik (from the top of my foggy head), there aren't any meta packages in there other than one or two CPAN related things for Perl. The meta packages in ::gentoo that I can remember from the top of my head are things like gnome-base/gnome and kde-plasma/plasma-meta. I am not overly bothered which category it goes in though.

wrt naming, adjust-infrastructure works for me. 

Failing checks are due to HOMEPAGE and LICENSE having 'TODO' in them. Will fix up in the morning.

**Comment by alip** [comment]
+1 for virtual CATEGORY & adjust-infrastructure PN.

**Comment by xmhd** [comment]
Renamed the PN and moved to virtual category. Also removed HOMEPAGE and LICENSE, so the errors on this PR will be gone now :-)

**Comment by alip** [comment]
About CI checks: If we want to keep using stable keywords unconditionally, it makes sense to disable the repoman check which throws a fatal error for adding new ebuilds with stable keywords. @xmhd, do you know if there's a way to do that?

**Comment by xmhd** [comment]
> About CI checks: If we want to keep using stable keywords unconditionally, it makes sense to disable the repoman check which throws a fatal error for adding new ebuilds with stable keywords. @xmhd, do you know if there's a way to do that?

There is a repoman --straight-to-stable option which afaik, 'just works' as long as all of the dependencies are also stable. So I will need to mark all of the packages in my perl pull request as stable before this one will pass QA.

**Pull request merged**
