### PR TITLE
dev-go/golangci-lint-bin: created new ebuild

### PR DESCRIPTION
**Pull request by lemanchester**
Created ebuild to install golangci-lint

### CODE REVIEW

**Comment by lemanchester** [comment]
ohh... forgot I need to add the manifest and metadata so WIP for now

**Comment by lemanchester** [comment]
fixed @maxeaubrey   :)

**Comment by 65278** [comment]
This package RDEPENDS on glibc though, so this ebuild is slightly incorrect. Can be amended later.

**Comment by lemanchester** [comment]
added the glibc

**Pull request merged**
