### PR TITLE
add pgbouncer_exporter ebuild

### PR DESCRIPTION
**Pull request by zegeek**
pgbouncer_exporter is a prometheus exporter that scrapes pgbouncer  stats. This ebuild will allow us to deploy it and create dashboards in grafana for teams to monitor their pgbouncer activity
related to adjust/infrastructure#15178

### CODE REVIEW

**Comment by xmhd** [comment]
I'll package this from sources later as opposed to using pre-compiled binaries.

**Comment by zegeek** [comment]
As you wish dave! ping me when you finish it please!

**Comment by xmhd** [comment]
tested on ~amd64 , wfm

**Review by xmhd — APPROVED** [review]

**Comment by zegeek** [comment]
thanks dave.

**Pull request merged**
